# permissions for end users to edit angulars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: angular-editor-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - angulars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - angulars/status
  verbs:
  - get
