# permissions for end users to edit infiniteupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infiniteupgrade-editor-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - infiniteupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - infiniteupgrades/status
  verbs:
  - get
