# permissions for end users to view laravels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laravel-viewer-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - laravels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - laravels/status
  verbs:
  - get
