# permissions for end users to edit laravels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laravel-editor-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - laravels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - laravels/status
  verbs:
  - get
