# permissions for end users to view nextjs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextjs-viewer-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - nextjs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - nextjs/status
  verbs:
  - get
