# permissions for end users to edit nextjs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextjs-editor-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - nextjs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - nextjs/status
  verbs:
  - get
