# permissions for end users to view angulars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: angular-viewer-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - angulars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - angulars/status
  verbs:
  - get
