# permissions for end users to view reacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: react-viewer-role
rules:
- apiGroups:
  - projects.ronas.cloud
  resources:
  - reacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projects.ronas.cloud
  resources:
  - reacts/status
  verbs:
  - get
