apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for projects.ronas.cloud/v1alpha1, Kind: NextJS
##
- apiGroups:
  - projects.ronas.cloud
  resources:
  - nextjs
  - nextjs/status
  - nextjs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
##
## Rules for projects.ronas.cloud/v1alpha1, Kind: Laravel
##
- apiGroups:
  - projects.ronas.cloud
  resources:
  - laravels
  - laravels/status
  - laravels/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
  - "persistentvolumes"
  - "persistentvolumeclaims"
  - "configmaps"
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
- verbs:
  - "*"
  apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
- verbs:
  - "*"
  apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings

##
## Rules for projects.ronas.cloud/v1alpha1, Kind: React
##
- apiGroups:
  - projects.ronas.cloud
  resources:
  - reacts
  - reacts/status
  - reacts/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

#+kubebuilder:scaffold:rules
