apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: laravel
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "11.2.1"
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: "16.9.5"
  - name: namespace
    repository: https://ameijer.github.io/k8s-as-helm
    version: "1.1.0"