apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: laravel
type: application
version: 1.0.1
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "11.2.1"
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: "16.9.5"
  - name: soketi
    condition: soketi.enabled
    repository: https://helm.soketi.app
    version: "0.16.2"
