apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: laravel
type: application
version: 0.1.0
dependencies:
  - name: postgres
    repository: https://ronasit-charts.storage.googleapis.com
    version: "0.4"
  - name: redis
    repository: https://ronasit-charts.storage.googleapis.com
    version: "0.7"