apiVersion: v2
appVersion: 1.16.0
description: DEPRECATED Helm charts moved to https://ronasit.github.io/helm/
deprecated: true
name: laravel
type: application
version: 1.1.1
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "11.6.18"
  - name: mysql
    condition: mysql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "9.2.1"
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "16.9.5"
  - name: soketi
    condition: soketi.enabled
    repository: https://helm.soketi.app
    version: "0.16.2"
