apiVersion: projects.ronas.cloud/v1alpha1
kind: Laravel
metadata:
  name: sample-laravel
spec:
  ingress:
    enabled: false
  postgresql:
    enabled: true
    loadBalancer:
      enabled: true
      internal: false
  mysql:
    enabled: true 
    loadBalancer:
      enabled: true
  redis:
    enabled: true
    loadBalancer:
      enabled: true
      internal: false
  migration:
    enabled: false
  workers:
    enabled: false 
