apiVersion: projects.ronas.cloud/v1alpha1
kind: Laravel
metadata:
  name: laravel-empry-project
spec:
  image:
    repository: laravel-empty-project
    tag: latest
  ingress:
    host: laravel-empty-project.ronas.cloud
  cronjobs:
    enabled: true
    schedulers:
      - name: clear-set-password-hash
        cmd: "php /app/artisan clear:set-password-hash"