apiVersion: projects.ronas.cloud/v1alpha1
kind: Laravel
metadata:
  name: laravel-empry-project
spec:
  image:
    repository: gcr.io/ronas-cloud/laravel-empty-project
    tag: latest
  ingress:
    host: demo.next.ronasit.com