apiVersion: projects.ronas.cloud/v1alpha1
kind: Laravel
metadata:
  name: sample-laravel
spec:
  ingress:
    enabled: false
  postgresql:
    enabled: true
    enabledExternalAccess: true
  mysql:
    enabled: true 
    enabledExternalAccess: true 
  redis:
    enabled: true
    enabledExternalAccess: true
  migration:
    enabled: false
  workers:
    enabled: false 
