apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel.fullname" . }}-cronjob
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: {{ .Values.cronjobs.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.cronjobs.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "laravel.labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "laravel.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ include "laravel.fullname" . }}-cronjobs
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.cronjobs.resources | nindent 16 }}
              command:
                - sh
                - -c
                - {{ .Values.cronjobs.cmd }}
          restartPolicy: "Never"