{{- if .Values.cronjobs.enabled -}}
{{- $root := . -}}
{{- range .Values.cronjobs.schedulers }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ regexReplaceAll "_" .name "-" }}-cronjob
  labels:
    {{- include "laravel.labels" $root | nindent 4 }}
spec:
  schedule: "{{ .schedule | default $root.Values.cronjobs.defaultSchedule }}"
  concurrencyPolicy: "{{ .concurrencyPolicy | default $root.Values.cronjobs.defaultConcurrencyPolicy }}"
  startingDeadlineSeconds: {{ .startingDeadlineSeconds | default $root.Values.cronjobs.defaultStartingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default $root.Values.cronjobs.defaultsuccessfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "laravel.labels" $root | nindent 12 }}
        spec:
          {{- with $root.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "laravel.serviceAccountName" $root }}
          securityContext:
            {{- toYaml $root.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ regexReplaceAll "_" .name "-" }}-cronjob
              image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}
              resources:
                {{ toYaml ( .resources | default $root.Values.cronjobs.resources ) | indent 16 }}
              command:
                - sh
                - -c
                - {{ .cmd }}
          restartPolicy: "{{ .restartPolicy | default $root.Values.cronjobs.defaultRestartPolicy }}"
{{- end }}
{{- end }}
