apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-script-configmap
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/migration.sh").AsConfig | indent 2 }}