{{- if and .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-migration
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    spec:
     {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "laravel.fullname" . }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: gcs
            mountPath: "/mnt/gcs"
            readOnly: true
          - name: scripts
            mountPath: "/mnt/scripts"
        resources:
{{- toYaml .Values.migration.resources | nindent 12 }}
        command:
          - sh
          - -c
          - {{ .Values.migration.cmd }}
      restartPolicy: Never
      volumes:
        - name: gcs
          secret:
            secretName: gcs-key
            optional: true
        - name: scripts
          configMap:
            name: {{ include "laravel.fullname" . }}-scripts
            defaultMode: 0777
{{- end }}
