apiVersion: v1
kind: Secret
metadata:
  name: "postgresql-credentials"
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "secret" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "redis-credentials"
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "secret" | b64enc | quote }}
