{{- if and .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "mysql" .Values.mysql.nameOverride }}-credentials
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ "secret" | b64enc | quote }}
  mysql-replication-password: {{ "secret" | b64enc | quote }}
  mysql-password: {{ "secret" | b64enc | quote }}
{{- end -}}
