{{- if and .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "postgresql" .Values.postgresql.nameOverride }}-credentials
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "secret" | b64enc | quote }}
  postgres-password: {{ "secret" | b64enc | quote }}
{{- end -}}
