{{- if and .Values.redis.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "redis" .Values.redis.nameOverride }}-credentials
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "secret" | b64enc | quote }}
{{- end -}}
