# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/projects.ronas.cloud_nextjs.yaml
- bases/projects.ronas.cloud_laravels.yaml
- bases/projects.ronas.cloud_infiniteupgrades.yaml
#+kubebuilder:scaffold:crdkustomizeresource
