apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: infiniteupgrade
type: application
version: 0.1.0
dependencies:
  - name: subchart
    version: 0.1.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "11.2.1"